### ISSUE TITLE
Unable to get corners to work

### ISSUE THREAD

**Issue by Chaggerr** [KazaKazan/aura#1]
I'm a newbie so sorry if this is a dumb question, but comparing your live page to the downloaded code I don't see any differences with the corners (other than being in dark mode and I tried making the corners white), but I can't make them show up for me.

Also I was curious about making the center image randomly picked from a folder of images. I tried to work backwards from your existing code, but I'm too stupid.

Sorry if this is the wrong place to ask, I saw your stuff on /wg/ and figured it'd been too long since you last posted to ask there.

**Comment by FiratUsta** [comment]
Hey!

So, I wanna ask a couple questions just to understand your problem better.

1. Which browser are you using?
2. Do the corners show up on the live page or do they not show up both on the live page and when you download the code & host it yourself?
3. Do the corners not show up at all or do they not show up in a certain mode (dark mode/light mode etc.)

About picking images randomly, that's a good feature request. Could you make another issue with only that so I can mark this one closed when we figure out your problem with the corners and the other issue when I implement the feature?

**Comment by Chaggerr** [comment]
1. I'm using the latest chrome versioon
2. They show up on the live page, but not on my local version
3. They don't show up on either mode

**Comment by FiratUsta** [comment]
Okay I think I understand the problem now after some testing. 

Correct me if I'm wrong but I think you're testing the site without actually setting up a server, ie. just opening the .html file in your browser. Which causes the problem. The corner images are set in css using `mask-image` (or `webkit-mask-image`), with a url to the file of the corner image. When you just open the file without setting a local server the browser thinks you're trying to pull an off-site image, which is disabled for `mask-image` for security reasons, that in turn throws a CORS error. Regretfully, using `mask-image` here is required to be able to easily change the color of the corner decorations.

Some options on what you could do is:

1. Use the public instance of aura, which is still locally customizable using the commands.
2. Fork this repo and set up github pages for your own instance of aura, which you can then edit the html, css and the js of directly.
3. Set up a local server using something like Apache (you can find set up instructions for that on the internet depending on your OS).

I hope this helps, if you need help doing any of the above feel free to contact me at ahmetfiratusta@gmail.com
